/**
 * Credit-use estimates for the UI ("Opus ~N credits/hr", per-voice cost lines).
 * Generated by the SAME pricing code that bills (meter.ts), so an estimate can
 * never drift from a real charge — only the assumed usage profile can be wrong,
 * and that's what the pre-launch validation bead is for.
 *
 * The profile below is SEEDED FROM ONE MEASURED SESSION: a ~50-minute practice
 * (emotions + parts + compassionate, high verbosity, full context) with HISTORY
 * CACHING ON. Key facts from that measurement:
 *   - ~33 facilitator LLM turns; output ~2,700 tokens (~10k chars of speech).
 *   - Full transcript re-sent each turn, but with prefix caching the bulk
 *     (~115k) is cache-READS at ~0.1x; only new user text is fresh input and
 *     each turn's new content is a one-time cache CREATION.
 *   - Input:output volume is ~45:1 — input (mostly cache reads now) dominates,
 *     so cache pricing, not output, drives the model cost.
 * With one data point these are order-of-magnitude (±~35%). Refine as real
 * telemetry accumulates; the shape (heavy cached input, modest output) is the
 * durable part.
 */

import type { SessionUsage } from '@aloud/core/facilitation';
import type { ProviderId } from '../contract.js';
import { MARGIN_MULTIPLIER, priceSession, usdToCredits } from './meter.js';
import { allowedModels } from './providers.js';
import { ttsRateFor, ttsVoices } from './voices.js';

/** Representative ~50-min session, history-caching ON. See file header. */
export const TYPICAL_SESSION_MINUTES = 50;

export const TYPICAL_SESSION: SessionUsage = {
    llmCalls: 33,
    llmTokensIn: 4_000, // fresh (uncached) user text across turns
    llmTokensOut: 2_700, // facilitator speech (~10k chars)
    llmCacheRead: 115_000, // re-sent prefix, cached at ~0.1x
    llmCacheCreation: 7_500, // unique content written to cache once
    sttSeconds: 240, // ~4 min of actual user speech (VAD-segmented)
    ttsChars: 10_000, // facilitator speech, if spoken by cloud TTS
};

const PER_HOUR = 60 / TYPICAL_SESSION_MINUTES;

function round1(n: number): number {
    return Math.round(n * 10) / 10;
}

export interface LegEstimate {
    creditsPerSession: number;
    creditsPerHour: number;
    /** Underlying provider cost per hour, for transparency / denomination tuning. */
    retailUsdPerHour: number;
}

export interface ModelEstimate extends LegEstimate {
    provider: ProviderId;
    model: string;
}

export interface VoiceEstimate extends LegEstimate {
    voiceId: string;
    label: string;
}

/** LLM-only credits for the typical session (zero STT/TTS — those are separate
 *  legs the UI composes). */
export function estimateModels(): ModelEstimate[] {
    const llmOnly: SessionUsage = { ...TYPICAL_SESSION, sttSeconds: 0, ttsChars: 0 };
    return allowedModels().map((m) => {
        const cost = priceSession(m.provider, m.model, llmOnly);
        return {
            provider: m.provider,
            model: m.model,
            creditsPerSession: cost.credits,
            creditsPerHour: Math.ceil(cost.credits * PER_HOUR),
            retailUsdPerHour: round1(cost.retailUsd * PER_HOUR * 100) / 100,
        };
    });
}

/** Cloud STT (Groq Whisper) leg — model-independent. */
export function estimateStt(): LegEstimate {
    const sttOnly: SessionUsage = { ...TYPICAL_SESSION, llmCalls: 0, llmTokensIn: 0, llmTokensOut: 0, llmCacheRead: 0, llmCacheCreation: 0, ttsChars: 0 };
    // Any allowed model works as the pricing key; llm fields are zero.
    const m = allowedModels()[0]!;
    const cost = priceSession(m.provider, m.model, sttOnly);
    return {
        creditsPerSession: cost.credits,
        creditsPerHour: Math.ceil(cost.credits * PER_HOUR),
        retailUsdPerHour: round1(cost.retailUsd * PER_HOUR * 100) / 100,
    };
}

/** Per-voice TTS leg. Local engines come out at 0. */
export function estimateVoices(): VoiceEstimate[] {
    return ttsVoices().map((v) => {
        const usd = TYPICAL_SESSION.ttsChars * ttsRateFor(v.id);
        const creditsPerSession = usdToCredits(usd);
        return {
            voiceId: v.id,
            label: v.label,
            creditsPerSession,
            creditsPerHour: Math.ceil(creditsPerSession * PER_HOUR),
            retailUsdPerHour: round1(usd * MARGIN_MULTIPLIER * PER_HOUR * 100) / 100,
        };
    });
}
